[package]
name = "greg-ng"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0"
authors = ["projects@pvv.ntnu.no"]
readme = "README.md"
homepage = "https://git.pvv.ntnu.no/Grzegorz"
repository = "https://git.pvv.ntnu.no/Grzegorz/greg-ng"
description = "A shared music player system, utilizing mpv"
categories = ["multimedia"]
keywords = ["mpv", "music-player"]
autobins = false
autolib = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.104"
axum = { version = "0.8.9", features = ["macros", "ws"] }
clap = { version = "4.6.6", features = ["derive"] }
const_format = "0.2.36"
futures = "0.3.34"
mpvipc-async = { git = "https://git.pvv.ntnu.no/Grzegorz/mpvipc-async.git", branch = "main" }
nix = { version = "0.31", features = ["socket"] }
sd-notify = "0.5.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tempfile = "3.27.0"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "process", "signal"] }
toml = "1.1.4"
tower = "0.5.3"
tower-http = "0.7.0"
tracing = "0.1.44"
tracing-journald = "0.3.2"
tracing-subscriber = "0.3.23"
tungstenite = "0.30.0"
utoipa = { version = "5.5.0", features = ["axum_extras"] }
utoipa-axum = "0.2.0"
utoipa-swagger-ui = { version = "9.0.2", features = ["axum", "vendored"] }

[build-dependencies]
build-info-build = "0.0.46"
git2 = { version = "0.21.0", default-features = false }
time = { version = "0.3", features = ["formatting", "macros"] }

[profile.release]
strip = true
lto = true
codegen-units = 1

[[bin]]
name = "greg-ng"
bench = false
path = "src/main.rs"
